//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTrimestre3Asp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inventario2021Entities : DbContext
    {
        public inventario2021Entities()
            : base("name=inventario2021Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<compra> compras { get; set; }
        public virtual DbSet<producto> productoes { get; set; }
        public virtual DbSet<producto_compra> producto_compra { get; set; }
        public virtual DbSet<producto_imagen> producto_imagen { get; set; }
        public virtual DbSet<proveedor> proveedors { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<usuariorol> usuariorols { get; set; }
    }
}
