//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTrimestre3Asp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.compras = new HashSet<compra>();
            this.usuariorols = new HashSet<usuariorol>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage ="Diligencie el campo Nombre")]
        [StringLength (25, ErrorMessage ="El limite de caracteres es de 25")]
        public string nombre { get; set; }


        [Required(ErrorMessage = "Diligencie el campo Apellido")]
        [StringLength(25, ErrorMessage = "El limite de caracteres es de 25")]
        public string apellido { get; set; }


        [Required(ErrorMessage = "Diligencie el campo Fecha de Nacimiento")]
        public System.DateTime fecha_nacimiento { get; set; }


        [Required(ErrorMessage = "Diligencie el campo Email")]
        [EmailAddress]
        public string email { get; set; }


        [Required(ErrorMessage = "Diligencie el campo Password")]
        [StringLength(25, ErrorMessage = "El limite de caracteres es de 35")]
        public string password { get; set; }

    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compra> compras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuariorol> usuariorols { get; set; }
    }
}
